import type { KeywordLocation, KeywordRule } from "./types";

const ALL_LOCATIONS: readonly KeywordLocation[] = [
  "title",
  "url-path",
  "meta-description",
  "og-metadata",
  "tags",
  "body-text",
];

export const ENGLISH_SEED_RULES: readonly KeywordRule[] = [
  {
    id: "en-pornography-001",
    pattern: "hardcore pornography",
    category: "pornography",
    riskWeight: 95,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.95,
  },
  {
    id: "en-pornography-002",
    pattern: "free pornography videos",
    category: "pornography",
    riskWeight: 90,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.9,
  },
  {
    id: "en-explicit-sex-001",
    pattern: "explicit sex scene",
    category: "explicit-sex",
    riskWeight: 90,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.9,
  },
  {
    id: "en-explicit-sex-002",
    pattern: "explicit sexual intercourse",
    category: "explicit-sex",
    riskWeight: 92,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.92,
  },
  {
    id: "en-hentai-001",
    pattern: "hentai uncensored",
    category: "hentai",
    riskWeight: 88,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.88,
  },
  {
    id: "en-hentai-002",
    pattern: "hentai doujinshi collection",
    category: "hentai",
    riskWeight: 85,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.85,
  },
  {
    id: "en-rule34-001",
    pattern: "rule 34 content",
    category: "rule34",
    riskWeight: 85,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.85,
  },
  {
    id: "en-rule34-002",
    pattern: "rule34 gallery",
    category: "rule34",
    riskWeight: 85,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.85,
  },
  {
    id: "en-adult-content-001",
    pattern: "adult content explicit",
    category: "adult-content",
    riskWeight: 85,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.85,
  },
  {
    id: "en-adult-content-002",
    pattern: "explicit xxx",
    category: "adult-content",
    riskWeight: 80,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["normal", "strict", "maximum"],
    confidence: 0.8,
  },
  {
    id: "en-nudity-001",
    pattern: "full frontal nudity",
    category: "nudity",
    riskWeight: 65,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.75,
  },
  {
    id: "en-nudity-002",
    pattern: "nude photos leaked",
    category: "nudity",
    riskWeight: 60,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.7,
  },
  {
    id: "en-ecchi-001",
    pattern: "ecchi fan service",
    category: "ecchi",
    riskWeight: 55,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.65,
  },
  {
    id: "en-ecchi-002",
    pattern: "ecchi hot spring scene",
    category: "ecchi",
    riskWeight: 55,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.65,
  },
  {
    id: "en-erotic-001",
    pattern: "erotic massage video",
    category: "erotic",
    riskWeight: 60,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.7,
  },
  {
    id: "en-erotic-002",
    pattern: "erotic art nude",
    category: "erotic",
    riskWeight: 55,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.65,
  },
  {
    id: "en-uncensored-001",
    pattern: "uncensored adult scene",
    category: "uncensored",
    riskWeight: 65,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.72,
  },
  {
    id: "en-sexualized-content-001",
    pattern: "sexualized cosplay content",
    category: "sexualized-content",
    riskWeight: 55,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.6,
  },
  {
    id: "en-sexualized-content-002",
    pattern: "sexually suggestive pose",
    category: "sexualized-content",
    riskWeight: 55,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["strict", "maximum"],
    confidence: 0.6,
  },
  {
    id: "en-nsfw-001",
    pattern: "nsfw content warning",
    category: "nsfw",
    riskWeight: 40,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["maximum"],
    confidence: 0.5,
  },
  {
    id: "en-nsfw-002",
    pattern: "nsfw adult material",
    category: "nsfw",
    riskWeight: 40,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["maximum"],
    confidence: 0.5,
  },
  {
    id: "en-explicit-images-001",
    pattern: "explicit image gallery",
    category: "explicit-images",
    riskWeight: 35,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["maximum"],
    confidence: 0.45,
  },
  {
    id: "en-explicit-video-001",
    pattern: "explicit video clip",
    category: "explicit-video",
    riskWeight: 35,
    language: "en",
    locations: ALL_LOCATIONS,
    protectionLevels: ["maximum"],
    confidence: 0.45,
  },
];
